import os

from src.utils import stats
from unittest import TestCase

from src.data.local_data_loader import unpickle_neuron_db, DATA_ROOT_PATH

# for IDE test
TEST_DATA_ROOT_PATH = os.getcwd().replace('tests', DATA_ROOT_PATH)
# for pytest
if not TEST_DATA_ROOT_PATH.endswith(DATA_ROOT_PATH):
    TEST_DATA_ROOT_PATH += f'/{DATA_ROOT_PATH}'


class Test(TestCase):
    def test_format_for_display(self):
        self.assertEqual({
            'd1': {'a': '6,555'},
            'd2': {'b': None, 'c': 0.55}
        }, stats._format_for_display({
            'd1': {'a': 6555},
            'd2': {'b': None, 'c': 0.55}
        }))

    def test_compile_data(self):
        # empty data
        caption, data_stats, data_charts = stats.compile_data(
            data={}, search_query='test_query_1', case_sensitive=0, match_words=1, data_version='447')
        self.assertEqual("Stats for search query: 'test_query_1', match words, data version: 447", caption)
        self.assertEqual({'': {'- Classified': '0', '- Annotated': '0', 'Cells': '0'}}, data_stats)
        self.assertEqual({}, data_charts)

        # actual data
        neuron_db = unpickle_neuron_db('447', data_root_path=TEST_DATA_ROOT_PATH)
        caption, data_stats, data_charts = stats.compile_data(
            data=list(neuron_db.neuron_data.values()), search_query='test_query_2', case_sensitive=1, match_words=0,
            data_version='447')
        self.assertEqual("Stats for search query: 'test_query_2', case sensitive, data version: 447", caption)
        self.assertEqual({'': {'- Classified': '68,375', '- Annotated': '33,009', 'Cells': '68,375'},
                          'Top Classes': {'Ascending': '2,224',
                                          'Central Brain': '32,797',
                                          'Optic Lobe': '19,815',
                                          'Sensory': '4,752',
                                          'Visual Projection': '7,456'},
                          'Top Annotations': {'Kenyon_Cell_L': '2,586',
                                              'Kenyon_Cell_L*': '1,242',
                                              'Putative AN': '2,227',
                                              'antennal lobe olfactory and thermo/hygrosensory receptor neuron (ALRN)': '1,916',
                                              'putative fru': '1,130'}}, data_stats)
        self.assertEqual({'Input neuropils': [['Input neuropils', 'Count'],
                                              ['AL_L', 2099],
                                              ['AL_R', 2000],
                                              ['AME_L', 88],
                                              ['AME_R', 80],
                                              ['AMMC_L', 769],
                                              ['AMMC_R', 711],
                                              ['AOTU_L', 972],
                                              ['AOTU_R', 879],
                                              ['ATL_L', 351],
                                              ['ATL_R', 368],
                                              ['AVLP_L', 3727],
                                              ['AVLP_R', 3025],
                                              ['BU_L', 139],
                                              ['BU_R', 87],
                                              ['CAN_L', 248],
                                              ['CAN_R', 181],
                                              ['CRE_L', 1694],
                                              ['CRE_R', 1752],
                                              ['EB', 469],
                                              ['EPA_L', 533],
                                              ['EPA_R', 584],
                                              ['FB', 2129],
                                              ['FLA_L', 1138],
                                              ['FLA_R', 973],
                                              ['GA_L', 99],
                                              ['GA_R', 160],
                                              ['GNG', 6632],
                                              ['GOR_L', 620],
                                              ['GOR_R', 560],
                                              ['IB_L', 1116],
                                              ['IB_R', 1050],
                                              ['ICL_L', 2235],
                                              ['ICL_R', 2088],
                                              ['IPS_L', 2282],
                                              ['IPS_R', 2497],
                                              ['LAL_L', 1522],
                                              ['LAL_R', 1666],
                                              ['LH_L', 2565],
                                              ['LH_R', 2548],
                                              ['LOP_L', 3634],
                                              ['LOP_R', 1432],
                                              ['LO_L', 7277],
                                              ['LO_R', 5009],
                                              ['MB_CA_L', 2759],
                                              ['MB_CA_R', 2672],
                                              ['MB_ML_L', 1522],
                                              ['MB_ML_R', 2057],
                                              ['MB_PED_L', 1029],
                                              ['MB_PED_R', 1388],
                                              ['MB_VL_L', 664],
                                              ['MB_VL_R', 590],
                                              ['ME_L', 10493],
                                              ['ME_R', 5636],
                                              ['NO', 603],
                                              ['PB', 569],
                                              ['PLP_L', 3843],
                                              ['PLP_R', 4105],
                                              ['PRW', 1595],
                                              ['PVLP_L', 2824],
                                              ['PVLP_R', 3208],
                                              ['SAD', 3426],
                                              ['SCL_L', 2267],
                                              ['SCL_R', 2068],
                                              ['SIP_L', 1686],
                                              ['SIP_R', 1391],
                                              ['SLP_L', 3816],
                                              ['SLP_R', 3379],
                                              ['SMP_L', 3704],
                                              ['SMP_R', 3510],
                                              ['SPS_L', 3212],
                                              ['SPS_R', 2678],
                                              ['Unknown', 5067],
                                              ['VES_L', 1286],
                                              ['VES_R', 1286],
                                              ['WED_L', 1789],
                                              ['WED_R', 1449]],
                          'Input/Output hemispheres': [['Output regions', 'Count'],
                                                       ['Left/Left', 24163],
                                                       ['Left/Mid', 30],
                                                       ['Left/Mix', 1361],
                                                       ['Left/None', 839],
                                                       ['Left/Right', 141],
                                                       ['Mid/Left', 77],
                                                       ['Mid/Mid', 4116],
                                                       ['Mid/Mix', 427],
                                                       ['Mid/None', 515],
                                                       ['Mid/Right', 83],
                                                       ['Mix/Left', 903],
                                                       ['Mix/Mid', 1133],
                                                       ['Mix/Mix', 7993],
                                                       ['Mix/None', 240],
                                                       ['Mix/Right', 879],
                                                       ['None/Left', 765],
                                                       ['None/Mid', 984],
                                                       ['None/Mix', 706],
                                                       ['None/Right', 870],
                                                       ['Right/Left', 144],
                                                       ['Right/Mid', 23],
                                                       ['Right/Mix', 1314],
                                                       ['Right/None', 737],
                                                       ['Right/Right', 18190],
                                                       ['Unknown', 1742]],
                          'Neurotransmitter Types': [['Type', 'Count'],
                                                     ['ACH', 39110],
                                                     ['DA', 5722],
                                                     ['GABA', 9888],
                                                     ['GLUT', 11865],
                                                     ['OCT', 121],
                                                     ['SER', 1415],
                                                     ['Unknown', 254]],
                          'Num. Assigned Neuron Classes': [['Num Classes', 'Count'], ['1', 68375]],
                          'Output neuropils': [['Output neuropils', 'Count'],
                                               ['AL_L', 2606],
                                               ['AL_R', 2492],
                                               ['AME_L', 76],
                                               ['AME_R', 63],
                                               ['AMMC_L', 595],
                                               ['AMMC_R', 558],
                                               ['AOTU_L', 1007],
                                               ['AOTU_R', 895],
                                               ['ATL_L', 328],
                                               ['ATL_R', 385],
                                               ['AVLP_L', 3973],
                                               ['AVLP_R', 3137],
                                               ['BU_L', 73],
                                               ['BU_R', 47],
                                               ['CAN_L', 157],
                                               ['CAN_R', 118],
                                               ['CRE_L', 2211],
                                               ['CRE_R', 2291],
                                               ['EB', 411],
                                               ['EPA_L', 495],
                                               ['EPA_R', 589],
                                               ['FB', 1986],
                                               ['FLA_L', 963],
                                               ['FLA_R', 846],
                                               ['GA_L', 97],
                                               ['GA_R', 127],
                                               ['GNG', 6998],
                                               ['GOR_L', 672],
                                               ['GOR_R', 656],
                                               ['IB_L', 1129],
                                               ['IB_R', 1103],
                                               ['ICL_L', 2003],
                                               ['ICL_R', 1943],
                                               ['IPS_L', 2085],
                                               ['IPS_R', 2187],
                                               ['LAL_L', 1274],
                                               ['LAL_R', 1427],
                                               ['LH_L', 1881],
                                               ['LH_R', 1842],
                                               ['LOP_L', 3992],
                                               ['LOP_R', 1942],
                                               ['LO_L', 8190],
                                               ['LO_R', 5140],
                                               ['MB_CA_L', 1336],
                                               ['MB_CA_R', 1196],
                                               ['MB_ML_L', 2623],
                                               ['MB_ML_R', 2913],
                                               ['MB_PED_L', 1944],
                                               ['MB_PED_R', 2040],
                                               ['MB_VL_L', 1365],
                                               ['MB_VL_R', 1228],
                                               ['ME_L', 9389],
                                               ['ME_R', 4814],
                                               ['NO', 489],
                                               ['PB', 231],
                                               ['PLP_L', 3267],
                                               ['PLP_R', 3721],
                                               ['PRW', 1300],
                                               ['PVLP_L', 2742],
                                               ['PVLP_R', 3215],
                                               ['SAD', 2949],
                                               ['SCL_L', 1992],
                                               ['SCL_R', 1780],
                                               ['SIP_L', 1583],
                                               ['SIP_R', 1680],
                                               ['SLP_L', 3484],
                                               ['SLP_R', 3145],
                                               ['SMP_L', 3698],
                                               ['SMP_R', 3457],
                                               ['SPS_L', 3148],
                                               ['SPS_R', 2686],
                                               ['Unknown', 4073],
                                               ['VES_L', 1169],
                                               ['VES_R', 1174],
                                               ['WED_L', 1413],
                                               ['WED_R', 1181]]}, data_charts)
